project:
  type: website
  output-dir: docs

website:
  title: "Mario De Toma"
  favicon: favicon-32x32.png
  repo-url: https://github.com/mdt-ds/mdt_web
  navbar:
    background: dark
    logo: mdt_logo.png
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
      
  page-footer:
    left: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    center: "Copyright 2023, Mario De Toma" 
    right: 
      - icon: github
        href: https://github.com/mdt-ds
      - icon: twitter 
        href: https://twitter.com/mariodetoma 

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

filters:
  - quarto_version.lua

editor: source
